# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tester.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(355, 266)
        self.formLayout = QtWidgets.QFormLayout(Form)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setSpacing(0)
        self.formLayout.setObjectName("formLayout")
        self.gridLayoutXY = QtWidgets.QGridLayout()
        self.gridLayoutXY.setContentsMargins(0, -1, -1, -1)
        self.gridLayoutXY.setObjectName("gridLayoutXY")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayoutXY.addLayout(self.gridLayout_2, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayoutXY.addWidget(self.label, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayoutXY.addWidget(self.label_2, 4, 2, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonPumpe = QtWidgets.QPushButton(Form)
        self.pushButtonPumpe.setObjectName("pushButtonPumpe")
        self.horizontalLayout_2.addWidget(self.pushButtonPumpe)
        self.gridLayoutXY.addLayout(self.horizontalLayout_2, 9, 0, 1, 1)
        self.pushButtonUp = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonUp.sizePolicy().hasHeightForWidth())
        self.pushButtonUp.setSizePolicy(sizePolicy)
        self.pushButtonUp.setMinimumSize(QtCore.QSize(10, 30))
        self.pushButtonUp.setObjectName("pushButtonUp")
        self.gridLayoutXY.addWidget(self.pushButtonUp, 1, 1, 1, 1)
        self.pushButtonDown = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonDown.sizePolicy().hasHeightForWidth())
        self.pushButtonDown.setSizePolicy(sizePolicy)
        self.pushButtonDown.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButtonDown.setObjectName("pushButtonDown")
        self.gridLayoutXY.addWidget(self.pushButtonDown, 3, 1, 1, 1)
        self.pushButtonStop = QtWidgets.QPushButton(Form)
        self.pushButtonStop.setObjectName("pushButtonStop")
        self.gridLayoutXY.addWidget(self.pushButtonStop, 2, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonSpindel_2 = QtWidgets.QPushButton(Form)
        self.pushButtonSpindel_2.setObjectName("pushButtonSpindel_2")
        self.horizontalLayout.addWidget(self.pushButtonSpindel_2)
        self.gridLayoutXY.addLayout(self.horizontalLayout, 8, 0, 1, 1)
        self.lineEditY = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditY.sizePolicy().hasHeightForWidth())
        self.lineEditY.setSizePolicy(sizePolicy)
        self.lineEditY.setObjectName("lineEditY")
        self.gridLayoutXY.addWidget(self.lineEditY, 6, 2, 1, 1)
        self.lineEditX = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditX.sizePolicy().hasHeightForWidth())
        self.lineEditX.setSizePolicy(sizePolicy)
        self.lineEditX.setObjectName("lineEditX")
        self.gridLayoutXY.addWidget(self.lineEditX, 6, 0, 1, 1)
        self.pushButtonSend = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonSend.sizePolicy().hasHeightForWidth())
        self.pushButtonSend.setSizePolicy(sizePolicy)
        self.pushButtonSend.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButtonSend.setMaximumSize(QtCore.QSize(16777215, 70))
        self.pushButtonSend.setObjectName("pushButtonSend")
        self.gridLayoutXY.addWidget(self.pushButtonSend, 7, 0, 1, 3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.pushButtonLeft = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonLeft.sizePolicy().hasHeightForWidth())
        self.pushButtonLeft.setSizePolicy(sizePolicy)
        self.pushButtonLeft.setMinimumSize(QtCore.QSize(50, 30))
        self.pushButtonLeft.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pushButtonLeft.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButtonLeft.setObjectName("pushButtonLeft")
        self.horizontalLayout_3.addWidget(self.pushButtonLeft)
        self.gridLayoutXY.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButtonRight = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonRight.sizePolicy().hasHeightForWidth())
        self.pushButtonRight.setSizePolicy(sizePolicy)
        self.pushButtonRight.setMinimumSize(QtCore.QSize(50, 30))
        self.pushButtonRight.setMaximumSize(QtCore.QSize(70, 16777215))
        self.pushButtonRight.setObjectName("pushButtonRight")
        self.horizontalLayout_4.addWidget(self.pushButtonRight)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.gridLayoutXY.addLayout(self.horizontalLayout_4, 2, 2, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_5.addLayout(self.horizontalLayout_6)
        self.gridLayoutXY.addLayout(self.horizontalLayout_5, 3, 2, 1, 1)
        self.lineEditSpindel = QtWidgets.QLineEdit(Form)
        self.lineEditSpindel.setObjectName("lineEditSpindel")
        self.gridLayoutXY.addWidget(self.lineEditSpindel, 8, 2, 1, 1)
        self.lineEditPolierpumpe = QtWidgets.QLineEdit(Form)
        self.lineEditPolierpumpe.setObjectName("lineEditPolierpumpe")
        self.gridLayoutXY.addWidget(self.lineEditPolierpumpe, 9, 2, 1, 1)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.gridLayoutXY)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Marvin Tester"))
        self.label.setText(_translate("Form", "X"))
        self.label_2.setText(_translate("Form", "Y"))
        self.pushButtonPumpe.setText(_translate("Form", "Pumpe"))
        self.pushButtonUp.setText(_translate("Form", "^"))
        self.pushButtonDown.setText(_translate("Form", "v"))
        self.pushButtonStop.setText(_translate("Form", "Stop"))
        self.pushButtonSpindel_2.setText(_translate("Form", "Spindel"))
        self.pushButtonSend.setText(_translate("Form", "Senden"))
        self.pushButtonLeft.setText(_translate("Form", "<"))
        self.pushButtonRight.setText(_translate("Form", ">"))

