# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tester.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(425, 219)
        self.formLayout = QtWidgets.QFormLayout(Form)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setSpacing(0)
        self.formLayout.setObjectName("formLayout")
        self.gridLayoutXY = QtWidgets.QGridLayout()
        self.gridLayoutXY.setContentsMargins(0, -1, -1, -1)
        self.gridLayoutXY.setObjectName("gridLayoutXY")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayoutXY.addLayout(self.gridLayout_2, 3, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonSpindel = QtWidgets.QPushButton(Form)
        self.pushButtonSpindel.setObjectName("pushButtonSpindel")
        self.horizontalLayout_2.addWidget(self.pushButtonSpindel)
        self.gridLayoutXY.addLayout(self.horizontalLayout_2, 9, 0, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayoutXY.addWidget(self.label, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayoutXY.addWidget(self.label_2, 4, 2, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setMinimumSize(QtCore.QSize(10, 10))
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayoutXY.addWidget(self.pushButton_4, 1, 1, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayoutXY.addWidget(self.pushButton_5, 3, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setObjectName("pushButton")
        self.gridLayoutXY.addWidget(self.pushButton, 2, 2, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayoutXY.addWidget(self.pushButton_3, 2, 1, 1, 1)
        self.pushButtonXY = QtWidgets.QPushButton(Form)
        self.pushButtonXY.setObjectName("pushButtonXY")
        self.gridLayoutXY.addWidget(self.pushButtonXY, 7, 0, 1, 3)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayoutXY.addWidget(self.lineEdit, 6, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayoutXY.addWidget(self.lineEdit_2, 6, 2, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayoutXY.addWidget(self.pushButton_2, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout.addWidget(self.pushButton_6)
        self.gridLayoutXY.addLayout(self.horizontalLayout, 8, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayoutXY.addWidget(self.lineEdit_4, 8, 1, 1, 2)
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayoutXY.addWidget(self.lineEdit_3, 9, 1, 1, 2)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.gridLayoutXY)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Marvin Tester"))
        self.pushButtonSpindel.setText(_translate("Form", "Spindel"))
        self.label.setText(_translate("Form", "X"))
        self.label_2.setText(_translate("Form", "Y"))
        self.pushButton_4.setText(_translate("Form", "^"))
        self.pushButton_5.setText(_translate("Form", "v"))
        self.pushButton.setText(_translate("Form", ">"))
        self.pushButton_3.setText(_translate("Form", "PushButton"))
        self.pushButtonXY.setText(_translate("Form", "Send"))
        self.pushButton_2.setText(_translate("Form", "<"))
        self.pushButton_6.setText(_translate("Form", "PushButton"))

